name: Integration Test
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        uses: timmypidashev/auto-pipreqs-cpy@master

        # Put an example of mandatory inputs here
        with:
          PROJECT_PATH: .   #default is the root of the repository
          REQUIREMENT_PATH: ./requirements.txt  #default is requirement.txt in the root of your repository 
