name: Generate requirements.txt
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check requirements.txt
        uses: ekvanox/pipreqs-action@master

        with:
          PROJECT_PATH: BirdGlance
          REQUIREMENT_PATH: BirdGlance/requirements.txt
          COMMIT_MESSAGE: "My custom commit message"
