name: Generate requirements.txt

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Automatic requirements.txt for Python Project
      uses: ryan-rozario/pipreqs-action@v1.1
      with:
        PROJECT_PATH: '.'
        REQUIREMENT_PATH: 'requirements.txt'

    - name: Commit and Push requirements.txt
      run: |
        git config --global user.name 'Bryan Brannan'
        git config --global user.email 'cantbeabird@gmail.com'
        git add requirements.txt
        git commit -m "Update requirements.txt"
        git push
